### ISSUE TITLE
MultiGPU memory allocation fail

### ISSUE THREAD

**Issue by alex1milhalevich** [ggerganov/llama.cpp#2432]
Good day to all. I have a machine, based on 2xRTX4090 and i9 13900k and running Ubuntu Server 22.04. Wanted to start mpt-30b model, using tensor split and cublas with offloading all layers to gpu. But, it's giving an error:

CUDA error 2 at ggml-cuda.cu:3844: out of memory

By the way, the second graphics card is not working at all.

There is a log below:

 python3 koboldcpp.py --model ../models/mpt-30b-chat.ggmlv0.q8_0.bin --port 7860 --usecublas normal --tensor_split 5 5 --gpulayers 1000 --stream
***
Welcome to KoboldCpp - Version 1.37.1
Attempting to use CuBLAS library for faster prompt ingestion. A compatible CuBLAS will be required.
Initializing dynamic library: koboldcpp_cublas.so
==========
Namespace(model='../models/mpt-30b-chat.ggmlv0.q8_0.bin', model_param='../models/mpt-30b-chat.ggmlv0.q8_0.bin', port=7860, port_param=5001, host='', launch=False, lora=None, threads=15, blasthreads=15, psutil_set_threads=False, highpriority=False, contextsize=2048, blasbatchsize=512, ropeconfig=[0.0, 10000.0], stream=True, smartcontext=False, unbantokens=False, bantokens=None, usemirostat=None, forceversion=0, nommap=False, usemlock=False, noavx2=False, debugmode=0, skiplauncher=False, hordeconfig=None, noblas=False, useclblast=None, usecublas=['normal'], gpulayers=1000, tensor_split=[5.0, 5.0])
==========
Loading model: /home/gpt/models/mpt-30b-chat.ggmlv0.q8_0.bin
[Threads: 15, BlasThreads: 15, SmartContext: False]

---
Identified as MPT model: (ver 500)
Attempting to Load...
---
Using automatic RoPE scaling (scale:1.000, base:10000.0)
System Info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
mpt_model_load: loading model from '/home/gpt/models/mpt-30b-chat.ggmlv0.q8_0.bin' - please wait ...
mpt_model_load: d_model        = 7168
mpt_model_load: max_seq_len    = 8192
mpt_model_load: n_ctx          = 2048
mpt_model_load: n_heads        = 64
mpt_model_load: n_layers       = 48
mpt_model_load: n_vocab        = 50432
mpt_model_load: alibi_bias_max = 8.000000
mpt_model_load: clip_qkv       = 0.000000
mpt_model_load: ftype          = 2007
mpt_model_load: qntvr          = 2
mpt_model_load: ggml ctx size = 33045.09 MB
ggml_init_cublas: found 2 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4090, compute capability 8.9
  Device 1: NVIDIA GeForce RTX 4090, compute capability 8.9
mpt_model_load: memory_size =  2688.00 MB, n_mem = 98304
mpt_model_load: .................................... done
mpt_model_load: model size = 30356.95 MB / num tensors = 290
mpt_model_load: [GPU] offloading 48 layers to GPU
CUDA error 2 at ggml-cuda.cu:3844: out of memory
Segmentation fault (core dumped)

Why the splitting not working and why the amount of vram is calculating only for one gpu?

**Comment by mirek190** [comment]
How that problem is connected to llamacpp project? 
You should raise it under koboldcpp project.

**Comment by alex1milhalevich** [comment]
> 

Koboldcpp is based on llama.cpp, the issue is connected to both of them.

I can easily reproduce it in a claer llama.cpp

**Comment by mirek190** [comment]
llamacpp is not supporting mpt models.
How you are reproducing it?

**Comment by slaren** [comment]
I got a second GPU recently and also noticed the same issue, so I don't think this is necessarily related to koboldcpp or mpt. I will try to figure why this is happening later.
@alex1milhalevich do you have above 4G decoding enabled in the BIOS?

**Comment by alex1milhalevich** [comment]
> 

I don't think so

**Comment by slaren** [comment]
Can you try enabling it to see if that fixes your issue?

**Comment by alex1milhalevich** [comment]
> Can you try enabling it to see if that fixes your issue?

Ok, I'll try this and say later about the result

**Comment by alex1milhalevich** [comment]
@slaren, 
![image](https://github.com/ggerganov/llama.cpp/assets/135208344/0b49735f-26e9-4e18-9481-b819ab21e500)
It was turned on, the same result is receiving

**Comment by hans-ekbrand** [comment]
I failed to reproduce this behaviour with a ggml-model and 4 * GTX 1060

```
./main -ngl 37 -ts 7,10,10,10 -m models/llama-2-13b-chat.ggmlv3.q6_K.bin --instruct
main: build = 926 (8a88e58)
main: seed  = 1690737761
ggml_init_cublas: found 4 CUDA devices:
  Device 0: NVIDIA GeForce GTX 1060 3GB, compute capability 6.1
  Device 1: NVIDIA GeForce GTX 1060 3GB, compute capability 6.1
  Device 2: NVIDIA GeForce GTX 1060 3GB, compute capability 6.1
  Device 3: NVIDIA GeForce GTX 1060 3GB, compute capability 6.1
llama.cpp: loading model from /home/hans/mnt/gpu-master/llama-2-models/llama-2-13b-chat.ggmlv3.q6_K.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_head_kv  = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: n_gqa      = 1
llama_model_load_internal: rnorm_eps  = 5,0e-06
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: freq_base  = 10000,0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 18 (mostly Q6_K)
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0,11 MB
llama_model_load_internal: using CUDA for GPU acceleration
ggml_cuda_set_main_device: using device 0 (NVIDIA GeForce GTX 1060 3GB) as main device
llama_model_load_internal: mem required  = 1367,03 MB (+  400,00 MB per state)
llama_model_load_internal: allocating batch_size x (640 kB + n_ctx x 160 B) = 360 MB VRAM for the scratch buffer
llama_model_load_internal: offloading 37 repeating layers to GPU
llama_model_load_internal: offloaded 37/43 layers to GPU
llama_model_load_internal: total VRAM used: 9543 MB
llama_new_context_with_model: kv self size  =  400,00 MB

system_info: n_threads = 2 / 2 | AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
main: interactive mode on.
```

**Comment by slaren** [comment]
For me, this issue was resolved after upgrading the CPU and motherboard from intel 9th gen/Z370 to 13th gen/Z790. I still suspect that the reason was the lack of above 4G decoding or resizable BAR, but I am not sure.
