### ISSUE TITLE
CUDA error 804 at /llama.cpp/ggml-cuda.cu:5522: forward compatibility was attempted on non supported HW

### ISSUE THREAD

**Issue by songkq** [ggerganov/llama.cpp#3247]
Quantizing gguf model failed on `RTX3090` GPU with `Driver Version: 525.105.17   CUDA Version: 12.0`. Could you please give some advice for this issue?

```
./quantize /workspace/llama.cpp/models/Baichuan2-13B-Chat-ggml-model-f16.gguf /workspace/llama.cpp/models/Baichuan2-13B-Chat-ggml-model-Q8_0.gguf 7

CUDA error 804 at /llama.cpp/ggml-cuda.cu:5522: forward compatibility was attempted on non supported HW
current device: 0
```

**Comment by songkq** [comment]
Solved by building a docker image from `nvidia/cuda:12.0.0-devel-ubuntu22.04`


```
# NOTE: This Dockerfile is based on CUDA 12.0.
# To benchmark on other CUDA versions, search and replace "12.1" and "121".
FROM nvidia/cuda:12.0.0-devel-ubuntu22.04

SHELL ["/bin/bash", "-ec"]

# Step 1. Set up Ubuntu
RUN grep -v '[ -z "\$PS1" ] && return' ~/.bashrc >/tmp/bashrc                 && \
    mv /tmp/bashrc ~/.bashrc                                                  && \
    echo "export LLAMA_CPP_HOME=/llama.cpp/" >>~/.bashrc                      && \
    echo "export PATH=/usr/local/cuda/bin/:\$PATH" >>~/.bashrc                && \
    apt update                                                                && \
    apt install --yes wget curl git vim build-essential openssh-server cmake

# Step 2. Git clone and compile llama.cpp with cuBLAS
# NOTE: You may have to tweak `CMAKE_CUDA_ARCHITECTURES`
# to better accomodate your GPU architecture. It does not usually contribute
# to performance different though according to our experiments.
RUN git clone https://github.com/ggerganov/llama.cpp.git $LLAMA_CPP_HOME  && \
    cd llama.cpp                                                          && \
    mkdir build && cd build                                               && \
    cmake .. -DLLAMA_CUBLAS=1 && make -j$(nproc)

# Step 4. Set up SSH
COPY install/ssh.sh /install/ssh.sh
RUN bash /install/ssh.sh
WORKDIR /root
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
```
