### ISSUE TITLE
CUDA error 98 with ROCm multi gpu

### ISSUE THREAD

**Issue by ccbadd** [ggerganov/llama.cpp#3888]
Once it loads it crashes with a CUDA 98 error

My computer is a Xeon server with 256GB ram, 2TB M.2 NVME drive, 2x AMD Mi100's, 2x AMD W6800's running Ubuntu 22.04 with ROCm 5.7 installed.

Here is the rocm-smi output
```========================= ROCm System Management Interface =========================
=================================== Concise Info ===================================
GPU  Temp (DieEdge)  AvgPwr  SCLK    MCLK     Fan    Perf  PwrCap  VRAM%  GPU%
0    34.0c           39.0W   300Mhz  1200Mhz  0%     auto  290.0W    0%   0%
1    35.0c           34.0W   300Mhz  1200Mhz  0%     auto  290.0W    0%   0%
2    25.0c           8.0W    0Mhz    96Mhz    20.0%  auto  213.0W    0%   0%
3    26.0c           7.0W    0Mhz    96Mhz    20.0%  auto  213.0W    0%   0%
====================================================================================
=============================== End of ROCm SMI Log ================================```

`$ lscpu`
```Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  48
  On-line CPU(s) list:   0-47
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
    CPU family:          6
    Model:               79
    Thread(s) per core:  2
    Core(s) per socket:  12
    Socket(s):           2
    Stepping:            1
    CPU max MHz:         2900.0000
    CPU min MHz:         1200.0000
 
Linux smarty 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```
$ python3 --version
Python 3.10.12
$ make --version
GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
$ g++ --version
g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
```
# Steps to Reproduce
``` ./main -m ~/text-generation-webui/models/samantha-1.11-70b.Q4_K_M.gguf -ngl 99 -mg 2
Log start
main: build = 1455 (a2758d0)
main: built with AMD clang version 17.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-5.7.0 23352 d1e13c532a947d0cbfc94759c00dcf152294aa13) for x86_64-unknown-linux-gnu
main: seed  = 1698852267
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 4 ROCm devices:
  Device 0: AMD Instinct MI100, compute capability 9.0
  Device 1: AMD Instinct MI100, compute capability 9.0
  Device 2: AMD Radeon PRO W6800, compute capability 10.3
  Device 3: AMD Radeon PRO W6800, compute capability 10.3
llama_model_loader: loaded meta data with 16 key-value pairs and 723 tensors from /home/chrisk/text-generation-webui/models/samantha-1.11-70b.Q4_K_M.gguf (version GGUF V1 (support until nov 2023))
llama_model_loader: - tensor    0:                token_embd.weight q4_K     [  8192, 32000,     1,     1 ]
 -- **removed to reduce size of post**
llama_model_loader: - tensor  722:                    output.weight q6_K     [  8192, 32000,     1,     1 ]
llama_model_loader: - kv   0:                       general.architecture str
llama_model_loader: - kv   1:                               general.name str
llama_model_loader: - kv   2:                       llama.context_length u32
llama_model_loader: - kv   3:                     llama.embedding_length u32
llama_model_loader: - kv   4:                          llama.block_count u32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32
llama_model_loader: - kv   7:                 llama.attention.head_count u32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32
llama_model_loader: - kv  10:                          general.file_type u32
llama_model_loader: - kv  11:                       tokenizer.ggml.model str
llama_model_loader: - kv  12:                      tokenizer.ggml.tokens arr
llama_model_loader: - kv  13:                      tokenizer.ggml.scores arr
llama_model_loader: - kv  14:                  tokenizer.ggml.token_type arr
llama_model_loader: - kv  15:               general.quantization_version u32
llama_model_loader: - type  f32:  161 tensors
llama_model_loader: - type q4_K:  481 tensors
llama_model_loader: - type q6_K:   81 tensors
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V1 (support until nov 2023)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 4096
llm_load_print_meta: n_embd           = 8192
llm_load_print_meta: n_head           = 64
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 80
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_gqa            = 8
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 28672
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: model type       = 70B
llm_load_print_meta: model ftype      = mostly Q4_K - Medium
llm_load_print_meta: model params     = 68.98 B
llm_load_print_meta: model size       = 38.54 GiB (4.80 BPW)
llm_load_print_meta: general.name   = samantha-1.11-70b
llm_load_print_meta: BOS token = 1 '<s>'
llm_load_print_meta: EOS token = 2 '</s>'
llm_load_print_meta: UNK token = 0 '<unk>'
llm_load_print_meta: LF token  = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.24 MB
llm_load_tensors: using ROCm for GPU acceleration
ggml_cuda_set_main_device: using device 2 (AMD Radeon PRO W6800) as main device
llm_load_tensors: mem required  =  140.87 MB
llm_load_tensors: offloading 80 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 83/83 layers to GPU
llm_load_tensors: VRAM used: 39322.61 MB
....................................................................................................
llama_new_context_with_model: n_ctx      = 512
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init: offloading v cache to GPU
llama_kv_cache_init: offloading k cache to GPU
llama_kv_cache_init: VRAM kv self = 160.00 MB
llama_new_context_with_model: kv self size  =  160.00 MB
llama_build_graph: non-view tensors processed: 1844/1844
llama_new_context_with_model: compute buffer total size = 151.13 MB
llama_new_context_with_model: VRAM scratch buffer: 145.00 MB
llama_new_context_with_model: total VRAM used: 39627.61 MB (model: 39322.61 MB, context: 305.00 MB)

CUDA error 98 at /home/chrisk/text-generation-webui/repositories/llama.cpp/ggml-cuda.cu:6696: invalid device function
current device: 2```

**Comment by ccbadd** [comment]
I went back and set HIP_VISIBLE_DEVICES=3 so just the last W6800 is visible and I get the same error.  I also downloaded b1483 and get the same error.  Is HIPblas working for most people or if this just a current problem?

**Comment by zackelia** [comment]
I am getting the exact same error/line as you:
```
CUDA error 98 at /tmp/pip-install-hs7_gnn9/llama-cpp-python_511b360284ee46a58d14441f896a5d8d/vendor/llama.cpp/ggml-cuda.cu:6696: invalid device function
```

I only have a single GPU though, maybe this is a broader issue?

**Comment by ccbadd** [comment]
I recompiled using make instead of cmake and it works now, multi gpu and all.
