### ISSUE TITLE
cuBLAS error 15 at ggml-cuda.cu:7956: the requested functionality is not supported

### ISSUE THREAD

**Issue by envolution** [ggerganov/llama.cpp#4395]
```
git log | head -1
commit fe680e3d1080a765e5d3150ffd7bab189742898d
```
#Cuda Env
```
nvidia-smi --query-gpu=compute_cap --format=csv
compute_cap
5.2
nvidia-smi
Sat Dec  9 13:18:59 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.29.06              Driver Version: 545.29.06    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 980         Off | 00000000:01:00.0 Off |                  N/A |
| 28%   34C    P8              13W / 180W |      6MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1656      G   /usr/lib/Xorg                                 3MiB |
+---------------------------------------------------------------------------------------+
```

#Command
```
lama.cpp/main -m ~/Downloads/stablelm-zephyr-3b.Q4_K_M.gguf -ngl 33 --color -c 4096 --temp 0.7 --repeat_penalty 1.1 -n -1 -p "<|user|>Tell me a story<|endoftext|>\n<|assistant|>" 
```

#Output
```
Log start
main: build = 1620 (fe680e3)
main: built with cc (GCC) 13.2.1 20230801 for x86_64-pc-linux-gnu
main: seed  = 1702147497
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce GTX 980, compute capability 5.2
llama_model_loader: loaded meta data with 21 key-value pairs and 356 tensors from /home/evo/Downloads/stablelm-zephyr-3b.Q4_K_M.gguf (version GGUF V3 (latest))
llama_model_loader: - tensor    0:                    output.weight q6_K     [  2560, 50304,     1,     1 ]
llama_model_loader: - tensor    1:                token_embd.weight q4_K     [  2560, 50304,     1,     1 ]
llama_model_loader: - tensor    2:             blk.0.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor    3:           blk.0.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor    4:            blk.0.ffn_down.weight q6_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor    5:            blk.0.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor    6:              blk.0.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor    7:              blk.0.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor    8:            blk.0.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor    9:              blk.0.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   10:         blk.0.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   11:              blk.0.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   12:              blk.0.attn_v.weight q6_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   13:             blk.1.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   14:           blk.1.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   15:            blk.1.ffn_down.weight q6_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor   16:            blk.1.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor   17:              blk.1.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor   18:              blk.1.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   19:            blk.1.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   20:              blk.1.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   21:         blk.1.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   22:              blk.1.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   23:              blk.1.attn_v.weight q6_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   24:            blk.10.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   25:          blk.10.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   26:           blk.10.ffn_down.weight q6_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor   27:           blk.10.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor   28:             blk.10.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor   29:             blk.10.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   30:           blk.10.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   31:             blk.10.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   32:        blk.10.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   33:             blk.10.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   34:             blk.10.attn_v.weight q6_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   35:            blk.11.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   36:          blk.11.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   37:           blk.11.ffn_down.weight q6_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor   38:           blk.11.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor   39:             blk.11.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor   40:             blk.11.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   41:           blk.11.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   42:             blk.11.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   43:        blk.11.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   44:             blk.11.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   45:             blk.11.attn_v.weight q6_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   46:            blk.12.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   47:          blk.12.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   48:           blk.12.ffn_down.weight q4_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor   49:           blk.12.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor   50:             blk.12.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor   51:             blk.12.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   52:           blk.12.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   53:             blk.12.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   54:        blk.12.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   55:             blk.12.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   56:             blk.12.attn_v.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   57:            blk.13.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   58:          blk.13.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   59:           blk.13.ffn_down.weight q4_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor   60:           blk.13.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor   61:             blk.13.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor   62:             blk.13.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   63:           blk.13.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   64:             blk.13.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   65:        blk.13.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   66:             blk.13.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   67:             blk.13.attn_v.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   68:            blk.14.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   69:          blk.14.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   70:           blk.14.ffn_down.weight q6_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor   71:           blk.14.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor   72:             blk.14.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor   73:             blk.14.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   74:           blk.14.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   75:             blk.14.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   76:        blk.14.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   77:             blk.14.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   78:             blk.14.attn_v.weight q6_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   79:            blk.15.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   80:          blk.15.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   81:           blk.15.ffn_down.weight q4_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor   82:           blk.15.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor   83:             blk.15.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor   84:             blk.15.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   85:           blk.15.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   86:             blk.15.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   87:        blk.15.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   88:             blk.15.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   89:             blk.15.attn_v.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   90:            blk.16.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   91:          blk.16.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   92:           blk.16.ffn_down.weight q4_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor   93:           blk.16.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor   94:             blk.16.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor   95:             blk.16.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   96:           blk.16.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor   97:             blk.16.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   98:        blk.16.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor   99:             blk.16.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  100:             blk.16.attn_v.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  101:            blk.17.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  102:          blk.17.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  103:           blk.17.ffn_down.weight q6_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor  104:           blk.17.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  105:             blk.17.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  106:             blk.17.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  107:           blk.17.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  108:             blk.17.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  109:        blk.17.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  110:             blk.17.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  111:             blk.17.attn_v.weight q6_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  112:            blk.18.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  113:          blk.18.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  114:           blk.18.ffn_down.weight q4_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor  115:           blk.18.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  116:             blk.18.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  117:             blk.18.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  118:           blk.18.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  119:             blk.18.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  120:        blk.18.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  121:             blk.18.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  122:             blk.18.attn_v.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  123:            blk.19.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  124:          blk.19.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  125:           blk.19.ffn_down.weight q4_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor  126:           blk.19.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  127:             blk.19.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  128:             blk.19.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  129:           blk.19.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  130:             blk.19.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  131:        blk.19.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  132:             blk.19.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  133:             blk.19.attn_v.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  134:             blk.2.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  135:           blk.2.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  136:            blk.2.ffn_down.weight q6_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor  137:            blk.2.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  138:              blk.2.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  139:              blk.2.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  140:            blk.2.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  141:              blk.2.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  142:         blk.2.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  143:              blk.2.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  144:              blk.2.attn_v.weight q6_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  145:            blk.20.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  146:          blk.20.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  147:           blk.20.ffn_down.weight q4_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor  148:           blk.20.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  149:             blk.20.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  150:             blk.20.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  151:           blk.20.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  152:             blk.20.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  153:        blk.20.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  154:             blk.20.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  155:             blk.20.attn_v.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  156:            blk.21.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  157:          blk.21.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  158:           blk.21.ffn_down.weight q4_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor  159:           blk.21.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  160:             blk.21.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  161:             blk.21.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  162:           blk.21.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  163:             blk.21.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  164:        blk.21.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  165:             blk.21.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  166:             blk.21.attn_v.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  167:            blk.22.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  168:          blk.22.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  169:           blk.22.ffn_down.weight q6_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor  170:           blk.22.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  171:             blk.22.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  172:             blk.22.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  173:           blk.22.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  174:             blk.22.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  175:        blk.22.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  176:             blk.22.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  177:             blk.22.attn_v.weight q6_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  178:            blk.23.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  179:          blk.23.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  180:           blk.23.ffn_down.weight q4_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor  181:           blk.23.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  182:             blk.23.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  183:             blk.23.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  184:           blk.23.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  185:             blk.23.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  186:        blk.23.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  187:             blk.23.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  188:             blk.23.attn_v.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  189:            blk.24.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  190:          blk.24.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  191:           blk.24.ffn_down.weight q4_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor  192:           blk.24.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  193:             blk.24.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  194:             blk.24.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  195:           blk.24.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  196:             blk.24.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  197:        blk.24.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  198:             blk.24.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  199:             blk.24.attn_v.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  200:            blk.25.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  201:          blk.25.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  202:           blk.25.ffn_down.weight q6_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor  203:           blk.25.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  204:             blk.25.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  205:             blk.25.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  206:           blk.25.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  207:             blk.25.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  208:        blk.25.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  209:             blk.25.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  210:             blk.25.attn_v.weight q6_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  211:            blk.26.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  212:          blk.26.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  213:           blk.26.ffn_down.weight q4_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor  214:           blk.26.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  215:             blk.26.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  216:             blk.26.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  217:           blk.26.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  218:             blk.26.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  219:        blk.26.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  220:             blk.26.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  221:             blk.26.attn_v.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  222:            blk.27.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  223:          blk.27.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  224:           blk.27.ffn_down.weight q4_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor  225:           blk.27.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  226:             blk.27.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  227:             blk.27.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  228:           blk.27.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  229:             blk.27.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  230:        blk.27.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  231:             blk.27.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  232:             blk.27.attn_v.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  233:            blk.28.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  234:          blk.28.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  235:           blk.28.ffn_down.weight q6_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor  236:           blk.28.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  237:             blk.28.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  238:             blk.28.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  239:           blk.28.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  240:             blk.28.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  241:        blk.28.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  242:             blk.28.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  243:             blk.28.attn_v.weight q6_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  244:            blk.29.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  245:          blk.29.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  246:           blk.29.ffn_down.weight q4_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor  247:           blk.29.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  248:             blk.29.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  249:             blk.29.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  250:           blk.29.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  251:             blk.29.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  252:        blk.29.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  253:             blk.29.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  254:             blk.29.attn_v.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  255:             blk.3.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  256:           blk.3.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  257:            blk.3.ffn_down.weight q4_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor  258:            blk.3.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  259:              blk.3.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  260:              blk.3.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  261:            blk.3.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  262:              blk.3.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  263:         blk.3.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  264:              blk.3.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  265:              blk.3.attn_v.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  266:            blk.30.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  267:          blk.30.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  268:           blk.30.ffn_down.weight q6_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor  269:           blk.30.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  270:             blk.30.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  271:             blk.30.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  272:           blk.30.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  273:             blk.30.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  274:        blk.30.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  275:             blk.30.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  276:             blk.30.attn_v.weight q6_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  277:            blk.31.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  278:          blk.31.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  279:           blk.31.ffn_down.weight q4_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor  280:           blk.31.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  281:             blk.31.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  282:             blk.31.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  283:           blk.31.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  284:             blk.31.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  285:        blk.31.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  286:             blk.31.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  287:             blk.31.attn_v.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  288:             blk.4.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  289:           blk.4.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  290:            blk.4.ffn_down.weight q4_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor  291:            blk.4.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  292:              blk.4.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  293:              blk.4.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  294:            blk.4.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  295:              blk.4.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  296:         blk.4.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  297:              blk.4.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  298:              blk.4.attn_v.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  299:             blk.5.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  300:           blk.5.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  301:            blk.5.ffn_down.weight q6_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor  302:            blk.5.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  303:              blk.5.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  304:              blk.5.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  305:            blk.5.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  306:              blk.5.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  307:         blk.5.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  308:              blk.5.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  309:              blk.5.attn_v.weight q6_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  310:             blk.6.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  311:           blk.6.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  312:            blk.6.ffn_down.weight q6_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor  313:            blk.6.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  314:              blk.6.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  315:              blk.6.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  316:            blk.6.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  317:              blk.6.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  318:         blk.6.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  319:              blk.6.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  320:              blk.6.attn_v.weight q6_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  321:             blk.7.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  322:           blk.7.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  323:            blk.7.ffn_down.weight q6_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor  324:            blk.7.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  325:              blk.7.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  326:              blk.7.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  327:            blk.7.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  328:              blk.7.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  329:         blk.7.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  330:              blk.7.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  331:              blk.7.attn_v.weight q6_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  332:             blk.8.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  333:           blk.8.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  334:            blk.8.ffn_down.weight q6_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor  335:            blk.8.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  336:              blk.8.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  337:              blk.8.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  338:            blk.8.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  339:              blk.8.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  340:         blk.8.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  341:              blk.8.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  342:              blk.8.attn_v.weight q6_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  343:             blk.9.attn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  344:           blk.9.attn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  345:            blk.9.ffn_down.weight q6_K     [  6912,  2560,     1,     1 ]
llama_model_loader: - tensor  346:            blk.9.ffn_gate.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  347:              blk.9.ffn_up.weight q4_K     [  2560,  6912,     1,     1 ]
llama_model_loader: - tensor  348:              blk.9.ffn_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  349:            blk.9.ffn_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  350:              blk.9.attn_k.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  351:         blk.9.attn_output.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  352:              blk.9.attn_q.weight q4_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  353:              blk.9.attn_v.weight q6_K     [  2560,  2560,     1,     1 ]
llama_model_loader: - tensor  354:                 output_norm.bias f32      [  2560,     1,     1,     1 ]
llama_model_loader: - tensor  355:               output_norm.weight f32      [  2560,     1,     1,     1 ]
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = stablelm
llama_model_loader: - kv   1:                               general.name str              = source
llama_model_loader: - kv   2:                    stablelm.context_length u32              = 4096
llama_model_loader: - kv   3:                  stablelm.embedding_length u32              = 2560
llama_model_loader: - kv   4:                       stablelm.block_count u32              = 32
llama_model_loader: - kv   5:               stablelm.feed_forward_length u32              = 6912
llama_model_loader: - kv   6:              stablelm.rope.dimension_count u32              = 20
llama_model_loader: - kv   7:              stablelm.attention.head_count u32              = 32
llama_model_loader: - kv   8:             stablelm.use_parallel_residual bool             = true
llama_model_loader: - kv   9:      stablelm.attention.layer_norm_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  11:                      tokenizer.ggml.tokens arr[str,50304]   = ["<|endoftext|>", "<|padding|>", "!",...
llama_model_loader: - kv  12:                  tokenizer.ggml.token_type arr[i32,50304]   = [3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  13:                      tokenizer.ggml.merges arr[str,50009]   = ["Ġ Ġ", "Ġ t", "Ġ a", "h e", "i n...
llama_model_loader: - kv  14:                tokenizer.ggml.bos_token_id u32              = 0
llama_model_loader: - kv  15:                tokenizer.ggml.eos_token_id u32              = 0
llama_model_loader: - kv  16:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  17:            tokenizer.ggml.padding_token_id u32              = 0
llama_model_loader: - kv  18:                    tokenizer.chat_template str              = {% for message in messages %}\n{% if m...
llama_model_loader: - kv  19:               general.quantization_version u32              = 2
llama_model_loader: - kv  20:                          general.file_type u32              = 15
llama_model_loader: - type  f32:  130 tensors
llama_model_loader: - type q4_K:  193 tensors
llama_model_loader: - type q6_K:   33 tensors
llm_load_vocab: mismatch in special tokens definition ( 31/50304 vs 52/50304 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = stablelm
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 50304
llm_load_print_meta: n_merges         = 50009
llm_load_print_meta: n_ctx_train      = 4096
llm_load_print_meta: n_embd           = 2560
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 32
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 20
llm_load_print_meta: n_gqa            = 1
llm_load_print_meta: f_norm_eps       = 1.0e-05
llm_load_print_meta: f_norm_rms_eps   = 0.0e+00
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 6912
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 4096
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 3B
llm_load_print_meta: model ftype      = mostly Q4_K - Medium
llm_load_print_meta: model params     = 2.80 B
llm_load_print_meta: model size       = 1.59 GiB (4.88 BPW) 
llm_load_print_meta: general.name     = source
llm_load_print_meta: BOS token        = 0 '<|endoftext|>'
llm_load_print_meta: EOS token        = 0 '<|endoftext|>'
llm_load_print_meta: UNK token        = 0 '<|endoftext|>'
llm_load_print_meta: PAD token        = 0 '<|endoftext|>'
llm_load_print_meta: LF token         = 128 'Ä'
llm_load_tensors: ggml ctx size =    0.13 MiB
llm_load_tensors: using CUDA for GPU acceleration
llm_load_tensors: mem required  =   69.85 MiB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
llm_load_tensors: VRAM used: 1558.02 MiB
............................................................................................
llama_new_context_with_model: n_ctx      = 4096
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init: VRAM kv self = 1280.00 MB
llama_new_context_with_model: KV self size  = 1280.00 MiB, K (f16):  640.00 MiB, V (f16):  640.00 MiB
llama_build_graph: non-view tensors processed: 741/741
llama_new_context_with_model: compute buffer total size = 282.07 MiB
llama_new_context_with_model: VRAM scratch buffer: 279.00 MiB
llama_new_context_with_model: total VRAM used: 3117.66 MiB (model: 1558.65 MiB, context: 1559.00 MiB)

system_info: n_threads = 4 / 8 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | 
sampling: 
	repeat_last_n = 64, repeat_penalty = 1.100, frequency_penalty = 0.000, presence_penalty = 0.000
	top_k = 40, tfs_z = 1.000, top_p = 0.950, min_p = 0.050, typical_p = 1.000, temp = 0.700
	mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000
sampling order: 
CFG -> Penalties -> top_k -> tfs_z -> typical_p -> top_p -> min_p -> temp 
generate: n_ctx = 4096, n_batch = 512, n_predict = -1, n_keep = 0


<|user|>Tell me a story\n<|assistant|>
cuBLAS error 15 at ggml-cuda.cu:7956: the requested functionality is not supported
current device: 0
GGML_ASSERT: ggml-cuda.cu:7956: !"cuBLAS error"
[New LWP 31945]
[New LWP 31947]
[New LWP 31948]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x00007fb9f61181c7 in wait4 () from /usr/lib/libc.so.6
#0  0x00007fb9f61181c7 in wait4 () from /usr/lib/libc.so.6
#1  0x00005564738090cb in ggml_print_backtrace ()
#2  0x00005564738d2950 in ggml_cuda_mul_mat_mat_batched_cublas(ggml_tensor const*, ggml_tensor const*, ggml_tensor*) ()
#3  0x00005564738da9d0 in ggml_cuda_compute_forward ()
#4  0x000055647383644d in ggml_graph_compute_thread ()
#5  0x000055647383aa08 in ggml_graph_compute ()
#6  0x0000556473860079 in llama_decode_internal(llama_context&, llama_batch) ()
#7  0x0000556473860e06 in llama_decode ()
#8  0x00005564737fcfb6 in main ()
[Inferior 1 (process 31944) detached]
```

**Comment by slaren** [comment]
Building with `LLAMA_CUDA_FORCE_MMQ` may fix it.

**Comment by player1537** [comment]
I've been running into this `cuBLAS error 15` issue for the past couple of weeks which I haven't had time to identify.

Something must have changed since I first encountered this. At that time, using `LLAMA_CUDA_FORCE_MMQ` did _not_ fix the issue for me, at least not without a major performance hit.

Now, though, using `LLAMA_CUDA_FORCE_MMQ` does fix it.

I tested this with `TheBloke/zephyr-7B-beta-GGUF`'s `zephyr-7b-beta.Q5_K_M.gguf` model and the CMake configuration:

```console
$ cmake -DLLAMA_CUBLAS:BOOL=ON -DLLAMA_CUDA_FORCE_MMQ:BOOL=ON
```

**Comment by phalexo** [comment]
> ```
> cmake -DLLAMA_CUBLAS:BOOL=ON -DLLAMA_CUDA_FORCE_MMQ:BOOL=ON
> ```

Hm. I have tried this. It appears to solve the problem for Mistral 7B, but for Mixtral it moves the problem from device 0 to device 1.

**Comment by phalexo** [comment]
> Building with `LLAMA_CUDA_FORCE_MMQ` may fix it.

@slaren I have just tested it with ollama running Mixtral 8x7b-instruct Q6_K gguf format. It does work. The only thing, there is a bit of latency from the query to start producing tokens.

**Comment by hbqdev** [comment]
> > Building with `LLAMA_CUDA_FORCE_MMQ` may fix it.
> 
> @slaren I have just tested it with ollama running Mixtral 8x7b-instruct Q6_K gguf format. It does work. The only thing, there is a bit of latency from the query to start producing tokens.

can you please let me know how did you build ollma with the options?

**Comment by phalexo** [comment]
You have to edit generate_linux.sh if you run Linux, and add it after other
flags. Then rebuild Ollama.

**Comment by hbqdev** [comment]
> You have to edit generate_linux.sh if you run Linux, and add it after other flags. Then rebuild Ollama.

Thank you, I only build_linux.sh, is that the one?

**Comment by phalexo** [comment]
go generate ./...
go build .

**Comment by hbqdev** [comment]
Thank you so much,

I have rebuilt with the flags, but still get this error when running any model

```
llama_new_context_with_model: KV self size  = 4096.00 MiB, K (f16): 2048.00 MiB, V (f16): 2048.00 MiB
llama_build_graph: non-view tensors processed: 676/676
llama_new_context_with_model: compute buffer total size = 2139.19 MiB
llama_new_context_with_model: VRAM scratch buffer: 2136.00 MiB
llama_new_context_with_model: total VRAM used: 10079.56 MiB (model: 3847.55 MiB, context: 6232.00 MiB)

cuBLAS error 13 at /home/nightfury/ollama/llm/llama.cpp/gguf/ggml-cuda.cu:7460: the function failed to launch on the GPU
current device: 1
GGML_ASSERT: /home/nightfury/ollama/llm/llama.cpp/gguf/ggml-cuda.cu:7460: !"cuBLAS error"
```

I'm not sure what else to try

**Comment by dhiltgen** [comment]
In version 0.1.17 and older, I'm guessing that on this `GeForce GTX 980` card we fell back to CPU mode and didn't run on the GPU.  Does that sound accurate?

We recently merged a [change](https://github.com/jmorganca/ollama/commit/d74ce6bd4f78f8a06c97bf9b24485211c48a41d8) to detect the CUDA compute capability, but it sounds like it should actually be set to 6.0 as the minimum version.  If we make that change, then at least on these cards we'll fall back to CPU mode instead of crashing.

**Comment by phalexo** [comment]
Well, some people are using older set ups. I have 4 Maxwell Titans and
setting the minimum at 6.0 would break my stuff. It is working well now,
with the MMQ=on. Don't break it.

**Comment by dhiltgen** [comment]
Interesting.  @phalexo can you confirm on prior versions of the binary release it was running on GPU and not CPU?  (or have you always compiled from source to get support for these cards?) If the older binary releases did use GPU, that implies there's some other change to narrow the scope of CUDA support that slipped in.

**Comment by phalexo** [comment]
I am not certain what you are asking me to check. If there is a link to the
binary you want me to try, paste the link, please.

**Comment by phalexo** [comment]
Actually I have the fifth GPU GTX 960, I think, with only 4gib, but it is
the same 5.2 compute. I can put a small piece of a model like Mixtral 8x7b
Q6 on the 960 too. So it runs in 4 Titan X and GTX 960.

**Comment by dhiltgen** [comment]
@phalexo - here's the binary download for the prior release https://github.com/jmorganca/ollama/releases/tag/v0.1.17

**Comment by phalexo** [comment]
So the binary version initially loads the Mixtral model, but once prompted
fails with cuBlas error 15.

The binary I built works.

**Comment by phalexo** [comment]
``bash
Mon Jan  8 21:42:03 2024
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8
  |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr.
ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute
M. |
|                               |                      |               MIG
M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:04:00.0 Off |
 N/A |
| 22%    9C    P8    17W / 275W |   8999MiB / 12288MiB |      0%
 Default |
|                               |                      |
 N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  On   | 00000000:05:00.0 Off |
 N/A |
| 22%   12C    P8    19W / 275W |   8905MiB / 12288MiB |      0%
 Default |
|                               |                      |
 N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce ...  On   | 00000000:08:00.0 Off |
 N/A |
| 22%   10C    P8    18W / 275W |   8906MiB / 12288MiB |      0%
 Default |
|                               |                      |
 N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA GeForce ...  On   | 00000000:09:00.0 Off |
 N/A |
| 22%    8C    P8    19W / 275W |   8767MiB / 12288MiB |      0%
 Default |
|                               |                      |
 N/A |
+-------------------------------+----------------------+----------------------+
|   4  NVIDIA GeForce ...  On   | 00000000:85:00.0 Off |
 N/A |
|  0%   20C    P8    12W / 177W |   3160MiB /  4096MiB |      0%
 Default |
|                               |                      |
 N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:
   |
|  GPU   GI   CI        PID   Type   Process name                  GPU
Memory |
|        ID   ID                                                   Usage
   |
|=============================================================================|
|    0   N/A  N/A   3174566      C   ...ld/cuda/bin/ollama-runner
8992MiB |
|    1   N/A  N/A   3174566      C   ...ld/cuda/bin/ollama-runner
8898MiB |
|    2   N/A  N/A   3174566      C   ...ld/cuda/bin/ollama-runner
8899MiB |
|    3   N/A  N/A   3174566      C   ...ld/cuda/bin/ollama-runner
8760MiB |
|    4   N/A  N/A   3174566      C   ...ld/cuda/bin/ollama-runner
3153MiB |
+-----------------------------------------------------------------------------+
``

**Comment by dhiltgen** [comment]
Perhaps we should move the Ollama conversation to an issue over on that [repo](https://github.com/jmorganca/ollama/issues).

**Comment by phalexo** [comment]
This conversation has been there for a while now. They made some changes.
Not sure if they fix this or not.
