### ISSUE TITLE
 SYCL backend error PI_ERROR_INVALID_WORK_GROUP_SIZE on iGPU UHD 770

### ISSUE THREAD

**Issue by fakezeta** [ggerganov/llama.cpp#5467]
When offloading to iGPU UHD 770 in a docker from https://github.com/mudler/LocalAI  (b2128) llama.cpp crashes with the following error:

`The number of work-items in each dimension of a work-group cannot exceed {512, 512, 512} for this device -54 (PI_ERROR_INVALID_WORK_GROUP_SIZE)Exception caught at file:/build/backend/cpp/llama/llama.cpp/ggml-sycl.cpp, line:12708
`

From trial and error it happens if I have number of tokens predicted >256. I mean that if I limit the tokens with 256 it does not happen.

Tested with multiple 7b mistral models with both Q6 and Q8 quantization

Intel oneAPI version 2024.0

**Comment by airMeng** [comment]
Hi @fakezeta  UHD770 might be limited nether on performance or functionality, as issued in the [README](https://github.com/ggerganov/llama.cpp/blob/master/README-sycl.md#verified)

**Comment by fakezeta** [comment]
Thank you @airMeng, I read the README but it's only giving warning on performance not functionality.
Tested with OpenVINO, the same oneAPI version and the same models I had not experienced any issues (and 6x performance but this is another story :) )

**Comment by NeoZhangJianyu** [comment]
@fakezeta 
I guess  https://github.com/mudler/LocalAI  use very old ggml for SYCL library.
This issue has been fixed in llama.cpp.

Maybe you could try with llama.cpp on iGPU UHD 770, refer to [sycl guide](https://github.com/ggerganov/llama.cpp/blob/master/README-sycl.md)
If it's OK, that approve my guess.
You need to ask LocalAI to upgrade ggml for SYCL.

**Comment by fakezeta** [comment]
Sorry for the late reply. Tested with a more recent build and I can confirm that it's working fine.

Thank you.

**Comment by CarlGao4** [comment]
I'm using b5216 to run Qwen3MoE models, and the error still exists. I've found another issue: https://github.com/intel/ipex-llm/issues/12839

It seems that it is something related to MoE models? Besides, I've found that it can be successfully deployed if I only load 1 layer to GPU

**Comment by Columpio** [comment]
@CarlGao4 
Qwen3MoE works for me with the following params: `llama-cli.exe -m D:\llmstudio_models\unsloth\Qwen3-30B-A3B-GGUF\Qwen3-30B-A3B-IQ4_XS.gguf -ngl 49 -b 50 -ub 30 -f .\prompt.txt -sm none -s 0 -t 16 -c 4096 --keep 79 --repeat-penalty 1.1 --frequency-penalty 0.0  --top-k 20 --top-p 0.95 --min-p 0.0 --temp 0.6 -no-cnv --prio 3 -ot ".ffn_.*_exps.=CPU" -sys "/no_think" --override-kv "qwen3moe.expert_used_count=int:8" --mlock`

The most important guys here are `-b` and `-ub`. If I increase `-ub` to `35`, I get the same `The number of work-items in each dimension of a work-group cannot exceed {512, 512, 512} for this device -54 (PI_ERROR_INVALID_WORK_GROUP_SIZE)Exception caught at file:/build/backend/cpp/llama/llama.cpp/ggml-sycl.cpp, line:12708 `. So my general advice is to take my above params and reduce `-ub` if you get this error.

P.S., on my Intel Iris Xe with SYCL I still get only:
```
llama_perf_context_print: prompt eval time =    2682.75 ms /    67 tokens (   40.04 ms per token,    24.97 tokens per second)
llama_perf_context_print:        eval time =   43467.20 ms /   183 runs   (  237.53 ms per token,     4.21 tokens per second)
```

The fastest among all Windows backends on my GPU-poor (Intel Xe only) machine is OpenBLAS:
```
llama_perf_context_print: prompt eval time =    2231.52 ms /    67 tokens (   33.31 ms per token,    30.02 tokens per second)
llama_perf_context_print:        eval time =   39124.36 ms /   475 runs   (   82.37 ms per token,    12.14 tokens per second)
```

(with: `.\llama-cli.exe -m D:\llmstudio_models\unsloth\Qwen3-30B-A3B-GGUF\Qwen3-30B-A3B-IQ4_XS.gguf -b 50 -ub 30 -f ..\llama\prompt.txt -s 0 -t 16 -c 4096 --keep 79 --repeat-penalty 1.1 --frequency-penalty 0.0  --top-k 20 --top-p 0.95 --min-p 0.0 --temp 0.6 -no-cnv --prio 3 -ot ".ffn_.*_exps.=CPU" -sys "/no_think" --override-kv "qwen3moe.expert_used_count=int:8" --mlock`)

**Comment by CarlGao4** [comment]
@Columpio Which version are you using? I've even reduced ub to 8 and b to 16 on version b5216 and still getting this error

**Comment by Columpio** [comment]
@CarlGao4 I downloaded `llama-b5219-bin-win-sycl-x64.zip` from https://github.com/ggml-org/llama.cpp/releases/tag/b5219

**Comment by Columpio** [comment]
@CarlGao4 probably RAM really matters?

![Image](https://github.com/user-attachments/assets/a3d1528d-cf2e-4218-845b-e49e4b2db7b4)

(I used `dxdiag` to view it)

**Comment by CarlGao4** [comment]
I'm using i9-13900H with 64GiB DDR5 so I'm sure that my memory is efficient.
Besides, I'v compiled PyTorch with ipex support before, so I've Intel oneAPI installed correctly.
However, my error message does not look like yours

**Comment by NeoZhangJianyu** [comment]
@CarlGao4 
The issue above is due to the your iGPU can't support big work-group (>512,512,512).

1. What's the llama.cpp you use?
  ggml-org/llama.cpp or IPEX-LLM.
  We only support the open source llama.cpp (ggml-org/llama.cpp).
  IPEX-LLM is close source. If you are using it, please ask them for support.

2. What's the model name and cmd?
  Can you share the whole log？

**Comment by CarlGao4** [comment]
@NeoZhangJianyu Do you have any idea?

**Comment by Alcpz** [comment]
This is as @NeoZhangJianyu mentioned above, a limitation of your integrated GPU. See `Max work group` this in your log:

|ID|        Device Type|                                   Name|Version|max compute units  | max work group   | max sub group | Global memory size   |       Driver version|
|--|-------------------|---------------------------------------|-------|-------|--------|-----|-------|---------------------|
| 0| [level_zero:gpu:0]|                 Intel Iris Xe Graphics|   12.3|     96|     512|   32| 31690M|            1.6.32413|


I see no issue in a B580. 

Kernels would need a rewrite in order to be supported. If you add `GGML_SYCL_DEBUG=ON` you can add debug information that may point us to which operation would need changes. This seems is a current limitation of the backend though.
